title: Guillaume De Gani # your name (or website title) here
logo: "/images/PhotoProf.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/guillaume-de-gani-73a301167//">LinkedIn</a> |
  <a href="https://github.com/guillaumedegani">GitHub</a>
  </p>
  I am pursing MS degree in computer science at the National School of Computer Science for Industry and Business in partnership with the University Of Paris-Saclay. 
  <br><br>
  Currently looking for a 6 month internship in the field of Machine Learning, Deep Learning or Data Science in the Bay area 
  <br><br>  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
minima:
  skin: dark
  date_format: "%b %-d, %Y"
